name: Deploy website
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    - name: npm install & build react app
      run: |
        npm install
        npm run build
        echo "auroraeditor.com" > build/CNAME
        cp build/index.html build/404.html
        cp -r src/Assets build/Assets
    - name: setup github env
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: push to Github Pages
      run: |
        git --work-tree build add --all
        git commit -m "Automatic Deploy action run by github-actions"
        git push origin HEAD:gh-pages --force
