# .github/workflows/deploy.yml
name: Deploy AuroraEditor Website Preview
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize    
jobs:
  deploy-preview:
    if: ${{ github.actor =! 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install and Build
        if: github.event.action != 'closed'
        run: |
          npm install
          npm run build
      
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          preview-branch: preview
          source-dir: .
          umbrella-dir: pr-preview
          action: auto
